# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.runs/synth_1/test_env.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.cache/wt} [current_project]
set_property parent.project_path {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {d:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib {
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/ANDgate.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/ANDgate_16bit.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/MPG.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/NANDgate_16bit.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/NORgate_16bit.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/NOTgate_16biti.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/NOTgate_1bit.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/NOTgate_4biti.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/NXORgate_16bit.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/ORgate3.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/ORgate_16bit.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/SSD.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/TESTeg.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/TESTgt.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/TESTisZero.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/TESTlt.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/XORgate3.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/XORgate_16bit.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/fullAdder_16bit.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/fullAdder_1bit.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/fullAdder_4bit.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/instructionDecode.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/instructionExecute.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/instructionFetch.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/leftLogicalRot.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/leftLogicalShift.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/mainUnit.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/memory.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/mux21_1bit.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/pozORneg.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/rightArithmShift_16biti.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/rightLogicalRot.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/rightLogicalShift.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/subtract_16bit.vhd}
  {D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/sources_1/new/test_env.vhd}
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/constrs_1/imports/test_env/as.xdc}}
set_property used_in_implementation false [get_files {{D:/OneDrive - Technical University of Cluj-Napoca/Desktop/utcn/anul 3/Sem 1 anul 3/SSC/Proiect SSC/ProiectSSC_VHDL/ProiectSSC_VHDL.srcs/constrs_1/imports/test_env/as.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top test_env -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef test_env.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file test_env_utilization_synth.rpt -pb test_env_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
